### ISSUE TITLE
Kidnapping women vs/ Kidnapping in general; separating women crimes

### ISSUE THREAD

**Issue by dannguyen** [crime-in-india/prototypes#11]
When reorganizing the table, it might be easier to separate it into **two** tables, one for normal crimes and ones designated as female-specific, because there might not be another clearer way to indicate that the per capita rates are calculated against the female population, all in the same table.

![image](https://cloud.githubusercontent.com/assets/121520/15557541/a52d1954-2288-11e6-93d2-054c24e1b458.png)

**Comment by ssdatar** [comment]
Done
