### ISSUE TITLE
Add .col-sm-6 to each front page column list of cities?

### ISSUE THREAD

**Issue by dannguyen** [crime-in-india/prototypes#12]
Seems like you could have the cities listed 2 columns across on the medium breakpoint: Right now, it collapses to one column:

![image](https://cloud.githubusercontent.com/assets/121520/15625133/e828e390-2450-11e6-98e9-834ed4f0844f.png)

Here's what it looks like with col-sm-6 (you can have each column be both .col-sm-6 and .col-md-4):

![image](https://cloud.githubusercontent.com/assets/121520/15625154/5e630c7a-2451-11e6-8f32-2b62d591a62c.png)

Also, you don't necessarily need multiple rows...one row for all of the columns should work, i.e. you don't need a row to separate each set of columns, that way the grid will take care of making it 3-rows across vs 2 rows

**Comment by ssdatar** [comment]
Done.
