### ISSUE TITLE
Table's columns are incorrect and links are broken for crime pages

### ISSUE THREAD

**Issue by dannguyen** [crime-in-india/prototypes#14]
The city name and crime names should be switched. And the city paths are broken, e.g. 

http://localhost:5000/Agra

(instead of http://localhost:5000/cities/Agra)

![image](https://cloud.githubusercontent.com/assets/121520/15698604/0f2a4a6a-277b-11e6-8998-100d077ab60b.png)

**Comment by ssdatar** [comment]
Done.
