### ISSUE TITLE
City pages need text explaining the numbers

### ISSUE THREAD

**Issue by dannguyen** [crime-in-india/prototypes#15]
One: There's nothing on the city pages indicating that the numbers are by rates.. 

Two: The women section especially needs a line saying that this is the rate calculated per 100,000 women according to the whatever Census you used. If someone has to jump to a different page to understand why your numbers are way out of line compared to the official numbers, they will assume that you've made a huge mistake. One line of text can prevent that:

![image](https://cloud.githubusercontent.com/assets/121520/15699146/ac4cc238-277f-11e6-85d0-5db4490dabd7.png)

I don't think things have to be a wall of text as you have them on the crime-category pages...you can have notes at the very bottom of the page (and those crime-category pages can be refactored too to not have 600+ words to read before showing a chart)

**Comment by ssdatar** [comment]
Moved to bottom, added lines.
