### ISSUE TITLE
Frontpage: Add dropdown menu/list of city names as alternative nav for map

### ISSUE THREAD

**Issue by dannguyen** [crime-in-india/prototypes#2]
Might even consider putting the list of city names, ranked by some metric, to serve as both nav and informational table, a la Chicago Trib's crimemapper:

![image](https://cloud.githubusercontent.com/assets/121520/15492129/e235d186-212c-11e6-838a-0c0e6c123bc6.png)

**Comment by ssdatar** [comment]
Added a dropdown. I really like this route too. Will add that as well.

**Comment by ssdatar** [comment]
Added list menu.
