### ISSUE TITLE
Violent crimes lead chart is problematic on smaller cities

### ISSUE THREAD

**Issue by dannguyen** [crime-in-india/prototypes#4]
The city of Malappuram has so few violent crimes that the lead chart is almost superfluous because of the empty space. Also, a line chart isn't ideal for showing year-to-year change, and with as few points on the x-axis as the chart has, the lines don't convey the numbers as clearly as they should.

![image](https://cloud.githubusercontent.com/assets/121520/15492286/7e1e46d6-212e-11e6-91e3-63cd95d2251c.png)

I recommend taking some time (including browsing through other data dashboards, whether they're crime related or not), and spending more time on thinking as the user, what the most important story is at the top of any given city page. Violent crime is usually what most people care about, but is the rate of crime over time the_only_ important thing? In the case of Malappuram, the fact that it's apparently safe makes the **riots** data stick out even more. For some people, that makes the city seem even more sketchy than if it had a few murders and other violent crimes to fill in the space.

Maybe another way to approach this is to not think of the lead image as having to cover the entire grid. There's very few data graphics that can pull that off, and the dataset here doesn't lend itself to such a spread. Even the Census Reporter, which is backed by gigabytes of data, breaks up the top of its page with 6 different visuals and arrangements, including the use of text to state the numbers more effectively than any chart can:

http://censusreporter.org/profiles/16000US0655282-palo-alto-ca/

![image](https://cloud.githubusercontent.com/assets/121520/15492404/bf27237c-212f-11e6-8017-cb483837ba84.png)

**Comment by ssdatar** [comment]
Changed this to a better chart. Also made the metro/non-metro charts to be on the same scale.
