### ISSUE TITLE
Tweak how the numbers are styled as tabular data

### ISSUE THREAD

**Issue by dannguyen** [crime-in-india/prototypes#5]
It's easier to compare numbers within a column if they're right-aligned rather than center-aligned...might even be worth using a monospace font so that the numbers line up uniformly.

![image](https://cloud.githubusercontent.com/assets/121520/15492795/05c6a632-2134-11e6-8f03-9fbfdd57548a.png)

In at least one place, there's floating point overflow...might just be easier to manually fix it if it's not a calculation:

![image](https://cloud.githubusercontent.com/assets/121520/15492826/4e15684c-2134-11e6-85ba-2fd7e87727a0.png)

**Comment by ssdatar** [comment]
Done.

**Comment by dannguyen** [comment]
Lookin good!
